[package]
name = "count_billion"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"

[[bench]]
name = "bench_billion"
harness = false

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
target-cpu = "native"
