"""
This type stub file was generated by pyright.
"""

from typing import final
from dsa_kuuking.types.nodes.LinkedListNode import LinkedListNode

@final
class DoublyLinkedListNode[T](LinkedListNode):
    def __init__(self, data: T) -> None:
        ...
    


