"""
This type stub file was generated by pyright.
"""

"""This module contains the type for Node used by linked lists classes"""
class LinkedListNode[T]:
    def __init__(self, data: T) -> None:
        ...
    
    @property
    def data(self) -> T:
        """Getter method for the data."""
        ...
    
    def get_id(self) -> int:
        """Retrieves the id of a node"""
        ...
    
    def __repr__(self): # -> str:
        ...
    


