"""
This type stub file was generated by pyright.
"""

from typing import TypeVar, Union
from dsa_kuuking.types.nodes.CircularLinkedListNode import CircularLinkedListNode
from dsa_kuuking.types.nodes.DoublyLinkedListNode import DoublyLinkedListNode
from dsa_kuuking.types.nodes.LinkedListNode import LinkedListNode

T = TypeVar("T", bound="NodeType")
NodeType = Union[CircularLinkedListNode, DoublyLinkedListNode[T], LinkedListNode[T]]
