"""
This type stub file was generated by pyright.
"""

class AttributeNotFoundException(Exception):
    """
    Exception raised when the attribute is not found in the node data.

    Attributes:
        message (str): Explanation of the error.
    """
    def __init__(self, attribute: str, message: str = ...) -> None:
        ...
    


