"""
This type stub file was generated by pyright.
"""

class InvalidSearchParameterException(Exception):
    """
    Exception raised for errors in the search parameter format.

    Attributes:
        message (str): Explanation of the error.
    """
    def __init__(self, message: str = ...) -> None:
        ...
    


