"""
This type stub file was generated by pyright.
"""

class LinkedListEmptyException(Exception):
    """
    Exception raised  when an operation is attempted on an empty LinkedList.

    Attributes:
        message (str): Explanation of the error.
    """
    def __init__(self, message: str = ...) -> None:
        ...
    


