"""
This type stub file was generated by pyright.
"""

class NodeNotFoundException(Exception):
    """
    Exception raised when a node with the specified data is not found in the LinkedList.

    Attributes:
        message (str): Explanation of the error.
    """
    def __init__(self, message: str = ...) -> None:
        ...
    


