"""
This type stub file was generated by pyright.
"""

class UnsupportedComparisonException(Exception):
    """
    Raised when a type does not support comparison operations.

    Attributes:
        message (str): A message describing the exception.
    """
    def __init__(self, message: str = ...) -> None:
        ...
    


