"""
This type stub file was generated by pyright.
"""

from typing import Dict, Iterable, List, Optional, Type, Union, override
from dsa_kuuking.interfaces.linked_list_interface import LinkedListInterface
from dsa_kuuking.types.nodes.LinkedListNode import LinkedListNode as Node
from dsa_kuuking.types.nodes.NodeType import NodeType
from dsa_kuuking.types.ResultType import ResultType

"""Contains the linked list class"""
class LinkedList[T](LinkedListInterface):
    """
    A generic singly linked list implementation.

    This class implements a singly linked list using nodes of type `Node[T]`.
    It supports operations such as adding nodes to the front or end of the list,
    removing nodes, and checking if the list is empty.

    Attributes:
        _head (Optional[Node[T]]): The head node of the linked list. Initialized to None.

    """
    def __init__(self, *args: Optional[T]) -> None:
        ...
    
    @override
    def add_to_front(self, data: Union[T, NodeType[T]]) -> Optional[ResultType[NodeType[T], str]]:
        """
        Adds a new node with the specified data to the front of the linked list.

        This method creates a new node containing the provided data and places it
        at the beginning of the list. The current head of the list becomes the next
        node of the newly added node.

        Args:
            data (T): The data to be stored in the new node. The type is specified
                      by the generic parameter `T`, allowing for any data type.

        Returns:
            None: This method does not return any value. It modifies the linked list
                  in place by updating the head node.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(10)
            >>> ll.add_to_front(5)
            # Now, the list is: 5 -> 10
        """
        ...
    
    @override
    def insert_node(self, data: Union[T, NodeType[T]], position: int) -> Optional[ResultType[NodeType[T], str]]:
        """
        Inserts a new node with the specified data at the given position in the linked list.

        This method creates a new node containing the provided data and places it at the
        specified position in the list. The position is zero-based, where 0 represents
        the head of the list. If the position is invalid (not an integer), a TypeError is raised.

        Args:
            data (Union[T, Node[T]]): The data to be stored in the new node. If a Node is provided,
                                      it will be inserted directly; otherwise, a new Node will be
                                      created with the given data.
            position (int): The zero-based index at which the new node should be inserted.
                            0 corresponds to inserting at the head of the list.

        Returns:
            Node[T]: The newly created or provided node that has been inserted into the linked list.

        Raises:
            TypeError: If the specified position is not an integer.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.insert_node(10, 0)
            >>> ll.insert_node(5, 1)
            # Now, the list is: 10 -> 5
        """
        ...
    
    @override
    def remove_by_id(self, node_id: int) -> Optional[NodeType[T]]:
        """
        Removes the node in the linked list with the specified unique ID.

        This method searches for the node in the linked list whose unique identifier
        matches the specified `node_id`. If such a node is found, it is removed from the
        list using the `remove_by_data` method, which handles edge cases and updates
        the list appropriately. The removed node is returned. If no node with the given
        ID is found, the method returns `None`.

        Args:
            node_id (int): The unique identifier of the node to be removed. This ID is
                           typically obtained from the `id()` function of a node instance.

        Returns:
            Optional[Node[T]]: The removed node if it is found; otherwise, `None`.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(10)
            >>> node = ll.add_to_front(5)
            >>> deleted_node = ll.remove_by_id(id(node))
            >>> deleted_node.data
            5
            >>> ll.get_size()
            1
            >>> ll.remove_by_id(999)  # Assuming 999 is not a valid ID
            Did not find the node to remove! Please, check your id for the node
            None
        """
        ...
    
    @override
    def remove_by_data(self, data: T) -> Optional[NodeType[T]]:
        """
       Removes the first node in the linked list that contains the specified data.

       This method searches for the first node in the linked list whose data matches
       the specified value. If such a node is found, it is removed from the list. If
       the node to be removed is the head, the head is updated. If the node is found
       elsewhere in the list, it is removed and the list is re-linked. The removed node
       is returned. If the list is empty or no such node is found, the method returns `None`.

       Args:
           data (T): The data value to search for in the linked list. The type is specified
                     by the generic parameter `T`, allowing for any data type.

       Returns:
           Optional[Node[T]]: The removed node if it is found; otherwise, `None`.

       Example:
           >>> ll = LinkedList[int]()
           >>> ll.add_to_front(10)
           >>> ll.add_to_front(5)
           >>> deleted_node = ll.remove_by_data(10)
           >>> deleted_node.data
           10
           >>> ll.get_size()
           1
           >>> ll.remove_by_data(15)
           Nothing to delete, because the list is empty!
           None
       """
        ...
    
    @override
    def remove_head(self) -> Optional[NodeType[T]]:
        """
        Removes the node at the head of the linked list.

        This method removes the node currently at the head of the list and updates the head
        to the next node in the list. If the list is empty, the method does nothing and returns
        `None`. The removed node is returned, which contains the data and ID of the removed node.

        Returns:
            Optional[Node[T]]: The removed node if the list is not empty. If the list is empty,
                                it returns `None`. The returned node contains the data and ID
                                of the removed node.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(10)
            >>> ll.add_to_front(5)
            >>> deleted_node = ll.remove_head()
            >>> deleted_node.data
            5
            >>> ll._head.data
            10
        """
        ...
    
    @override
    def is_empty(self) -> bool:
        """
        Checks if the linked list is empty.

        This method determines whether the linked list contains any nodes. It returns
        `True` if the list is empty (i.e., if the head of the list is `None`), and
        `False` otherwise.

        Returns:
            bool: `True` if the linked list is empty; `False` if it contains one or more nodes.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.is_empty()
            True
            >>> ll.add_to_front(10)
            >>> ll.is_empty()
            False
        """
        ...
    
    def has_head(self) -> bool:
        ...
    
    @override
    def get_head(self) -> ResultType[NodeType[T], str]:
        ...
    
    @override
    def get_size(self) -> int:
        """
        Returns the number of nodes in the linked list.

        This method provides the count of nodes currently present in the linked list.
        It returns an integer representing the number of nodes from the head to the end of the list.

        Returns:
            int: The number of nodes in the linked list.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(10)
            >>> ll.add_to_front(5)
            >>> ll.get_size()
            2
        """
        ...
    
    @override
    def display(self) -> None:
        ...
    
    @override
    def display_backwards(self) -> None:
        ...
    
    @override
    def find_by_id(self, node_id: int) -> Optional[NodeType[T]]:
        """
        Searches for a node in the linked list by its unique ID.

        This method traverses the linked list and looks for a node whose ID matches
        the specified `node_id`. If a node with the given ID is found, the method
        returns that node. If no node with the specified ID is found, the method
        returns -1.

        Args:
            node_id (int): The unique identifier of the node to search for. This ID is
                           typically obtained from the `id()` function of a node instance.

        Returns:
            Node[T] | int: The node with the specified ID if found; otherwise, returns
                           -1 to indicate that no such node exists. The returned node
                           contains the data and ID of the node.

        Example:
            >>> ll = LinkedList[int]()
            >>> node1 = Node(10)
            >>> node2 = Node(5)
            >>> ll.add_to_front(node1.data)
            >>> ll.add_to_front(node2.data)
            >>> found_node = ll.find_by_id(id(node1))
            >>> found_node.data
            10
            >>> ll.find_by_id(999)  # Assuming 999 is not a valid ID
            -1
        """
        ...
    
    @override
    def find_spot(self, target: NodeType[T]) -> Optional[NodeType[T]]:
        ...
    
    @override
    def find_by_data(self, data: T) -> int:
        """
        Searches for a node in the linked list by its data.

        This method traverses the linked list, looking for a node whose data matches the
        specified value. If a matching node is found, it returns the node. If no node
        with the specified data is found, it returns -1. The type of data is specified
        by the generic parameter `T`, which should support equality comparison.

        Args:
            data (T): The data to search for in the linked list. The type is specified
                      by the generic parameter `T`, allowing for any data type that
                      supports equality comparison.

        Returns:
            Node[T] | int: The node containing the specified data if found; otherwise,
                           returns -1. The returned node contains the data and ID of the node.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(10)
            >>> ll.add_to_front(5)
            >>> found_node_index = ll.find_by_data(10)
            >>> found_node_index
            1
            >>> ll.find_by_data(3)
            -1
        """
        ...
    
    @override
    def find_by_params(self, search_param: Dict[str, Union[str, int, float]]) -> Optional[NodeType[T]]:
        """
        Searches for a node in the linked list by a specified attribute and its value.

        This method traverses the linked list looking for a node where the attribute specified
        by the key in `search_param` matches the value given. It assumes that the attribute exists
        on the data and that the data type can handle comparison with the given value.

        Args:
            search_param (Dict[str, Union[str, int, float]]): A dictionary with a single key-value pair where
                                                              the key is the attribute name and the value is
                                                              the target value to search for. The value must
                                                              be a primitive type that can be compared.

        Returns:
            Optional[Node[T]]: The node containing the data with the specified attribute value if found;
                               otherwise, returns None.

        Example:
            >>> class Person:
            >>>     def __init__(self, name: str, age: int) -> None:
            >>>         self.name = name
            >>>         self.age = age
            >>>
            >>> ll = LinkedList[Person]()
            >>> ll.add_to_front(Person("Alice", 21))
            >>> ll.add_to_front(Person("Bob", 25))
            >>> found_node = ll.find_by_params({"name": "Alice"})
            >>> found_node.data.name
            "Alice"
            >>> ll.find_by_params({"age": 30}) is None
            True
        """
        ...
    
    @override
    def find_by_attribute(self, attribute_name: str, attribute_value: Union[str, int]) -> Optional[NodeType[T]]:
        """
        Searches for a node in the linked list by a specific attribute of its data.

        This method traverses the linked list looking for a node where the attribute specified
        by `attribute_name` matches the `attribute_value`. It assumes that the attribute exists
        on the data and that the data type can handle comparison with the given value.

        Args:
            attribute_name (str): The name of the attribute to search for in the data of the node.
            attribute_value (Union[str, int]): The value to match against the attribute. This must
                                               be a primitive type that can be compared.

        Returns:
            Node[T] | int: The node containing the data with the specified attribute value if found;
                           otherwise, returns -1.

        Example:
            >>> class Person:
            >>>     def __init__(self, name: str, age: int) -> None:
            >>>         self.name = name
            >>>         self.age = age
            >>>
            >>> ll = LinkedList[Person]()
            >>> ll.add_to_front(Person("Alice", 21))
            >>> ll.add_to_front(Person("Bob", 25))
            >>> found_node = ll.find_by_attribute('name', "Alice")
            >>> found_node.data.name
            "Alice"
            >>> ll.find_by_attribute('age', 30)
            -1
        """
        ...
    
    @override
    def traverse(self) -> Iterable[NodeType[T]]:
        """
       Iterates over all nodes in the linked list.

       This method yields each node in the linked list starting from the head and
       continuing to the end of the list. It allows for iteration over the nodes
       using a for-loop or any other iteration construct.

       Yields:
           Node[T]: The current node in the linked list during each iteration.

       Example:
           >>> ll = LinkedList[int]()
           >>> ll.add_to_front(10)
           >>> ll.add_to_front(5)
           >>> for node in ll.traverse():
           >>>     print(node.data)
           5
           10
       """
        ...
    
    @override
    def traverse_backwards(self) -> Iterable[NodeType[T]]:
        """
        Iterates over all nodes in the linked list in reverse order.

        This method yields each node in the linked list starting from the end and
        moving to the beginning of the list. It allows for reverse iteration over
        the nodes, but requires that the list be reversible. This is typically useful
        for lists where reversing the order of traversal is necessary.

        Yields:
            Node[T]: The current node in the linked list during each iteration,
                     starting from the last node and moving towards the head.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(1)
            >>> ll.add_to_front(2)
            >>> ll.add_to_front(3)
            >>> for traversed_node in ll.traverse_backwards():
            >>>     print(traversed_node.data)
            1
            2
            3
        """
        ...
    
    def concat(self, ll: LinkedList[T]) -> LinkedList[T]:
        """
        Concatenates the current linked list with another linked list.

        This method adds all nodes from the given linked list `ll` to the front of the current linked list.
        If the current linked list is empty, the nodes from `ll` are added directly to the current list.
        If `ll` is empty, the current list remains unchanged.

        Args:
            ll (LinkedList[T]): The linked list to be concatenated with the current list.

        Returns:
            LinkedList[T]: The current linked list after concatenation.

        Example:
            >>> linked_list_1 = LinkedList[int]()
            >>> linked_list_1.add_to_front(10)
            >>> linked_list_1.add_to_front(5)
            >>> linked_list_1.display()
            Node(data=5)->Node(data=10)

            >>> linked_list_2 = LinkedList[int]()
            >>> linked_list_2.add_to_front(15)
            >>> linked_list_2.add_to_front(20)
            >>> linked_list_2.display()
            Node(data=20)->Node(data=15)

            >>> linked_list_1.concat(linked_list_2)
            >>> linked_list_1.display()
            Node(data=15)->Node(data=20)->Node(data=5)->Node(data=10)

            # Additional Example
            >>> empty_list = LinkedList[int]()
            >>> linked_list_3 = LinkedList[int]()
            >>> linked_list_3.add_to_front(30)
            >>> linked_list_3.add_to_front(25)
            >>> linked_list_3.display()
            Node(data=25)->Node(data=30)

            >>> linked_list_3.concat(empty_list)
            >>> linked_list_3.display()
            Node(data=25)->Node(data=30)

            >>> linked_list_4 = LinkedList[int]()
            >>> linked_list_4.add_to_front(1)
            >>> linked_list_4.add_to_front(2)
            >>> linked_list_4.add_to_front(3)
            >>> linked_list_4.display()
            Node(data=3)->Node(data=2)->Node(data=1)

            >>> linked_list_4.concat(empty_list)
            >>> linked_list_4.display()
            Node(data=3)->Node(data=2)->Node(data=1)
        """
        ...
    
    def reverse(self) -> Optional[LinkedList[T]]:
        """
        Reverses the linked list in place.

        This method reverses the order of nodes in the linked list. After execution, the
        head of the list will point to what was previously the last node, and the tail will
        point to what was previously the head. The method operates in-place and does not
        require additional memory beyond a few pointers.

        If the list is empty (i.e., the head is `None`), the method returns `None` as there
        is nothing to reverse.

        Returns:
            Optional['LinkedList[T]']: The reversed linked list. Returns `None` if the
            list was empty.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(1) # tail
            >>> ll.add_to_front(2) # middle
            >>> ll.add_to_front(3) # head
            >>> ll.display()
            Node(data=3)->Node(data=2)->Node(data=1)
            >>> reversed_list = ll.reverse()
            >>> reversed_list.display()
            Node(data=1)->Node(data=2)->Node(data=3)
        """
        ...
    
    def swap_two_nodes(self, a: NodeType[T], b: NodeType[T]) -> Optional[ResultType[T, str]]:
        ...
    
    def to_list(self) -> List[Node[T]]:
        """
        Converts the current linked list instance to a Python list.

        This method converts the current linked list instance into a list
        containing the elements of the linked list in the same order.

        Returns:
            list: A list containing the elements of the linked list.

        Example:
            >>> linked_list = LinkedList[int]()
            >>> linked_list.add_to_front(1)
            >>> linked_list.add_to_front(2)
            >>> linked_list.add_to_front(3)
            >>> linked_list.to_list()
            [3, 2, 1]
        """
        ...
    
    @staticmethod
    def is_primitive_type(type_check: Type) -> bool:
        """
        Checks if the given type is a primitive type.

        This method determines whether the type specified by `type_check` is
        one of the primitive types: `int`, `float`, or `str`. It returns `True`
        if the type is among these primitive types and `False` otherwise.

        Args:
            type_check (Type): The type to check.

        Returns:
            bool: `True` if `type_check` is one of `int`, `float`, or `str`;
                  otherwise, `False`.

        Example:
            >>> LinkedList.is_primitive_type(int)
            True
            >>> LinkedList.is_primitive_type(float)
            True
            >>> LinkedList.is_primitive_type(str)
            True
            >>> LinkedList.is_primitive_type(list)
            False
            >>> LinkedList.is_primitive_type(dict)
            False
        """
        ...
    
    @staticmethod
    def to_list_static(ll: LinkedList[T]): # -> list[NodeType[Any]]:
        """
        Converts a linked list to a Python list.

        This method takes a linked list and returns a list containing the elements
        of the linked list in the same order.

        Args:
            ll (LinkedList[T]): The linked list to be converted.

        Returns:
            list: A list containing the elements of the linked list.

        Raises:
            ValueError: If the provided linked list is None.

        Example:
            >>> linked_list = LinkedList[int]()
            >>> linked_list.add_to_front(1)
            >>> linked_list.add_to_front(2)
            >>> linked_list.add_to_front(3)
            >>> LinkedList.to_list(ll)
            [3, 2, 1]
        """
        ...
    
    @staticmethod
    def from_list(iterable: Iterable[T]) -> LinkedList[T]:
        """
        Creates a linked list from an iterable.

        This method takes an iterable (e.g., list, queue) and returns a linked list
        containing the elements of the iterable in reverse order.

        Args:
            iterable (Iterable[T]): The iterable to be converted into a linked list.

        Returns:
            LinkedList[T]: A linked list containing the elements of the iterable.

        Raises:
            ValueError: If the provided iterable is empty or None.

        Example:
            >>> original_list = [1, 2, 3]
            >>> linked_list = LinkedList.from_list(original_list)
            >>> list(linked_list.traverse())
            [3, 2, 1]
        """
        ...
    
    def __contains__(self, item: NodeType[T]) -> bool:
        """
        Checks if the specified node is present in the linked list.

        This method allows checking for the existence of a node in the linked list using
        the `in` operator. It leverages an internal hash set to efficiently determine if
        the given node is part of the linked list.

        Args:
            item (Node[T]): The node to check for presence in the linked list.

        Returns:
            bool: True if the node is present in the linked list, False otherwise.

        Example:
            >>> ll = LinkedList[int]()
            >>> node1_result = ll.add_to_front(1)
            >>> node2_result = ll.add_to_front(2)
            >>> if node1_result.is_ok():
            >>>     node1_result.unwrap() in ll
            True
            >>> node3 = Node(3)
            >>> node3 in ll
            False
            >>> node4 = Node(2)
            >>> node4 in ll # because node4.next is None, while node2.next is node1
            False
        """
        ...
    
    def __len__(self) -> int:
        """
        Returns the number of elements in the linked list (length).

        This method provides the size of the linked list, which is the total number of nodes
        present in the list. It allows the use of Python's built-in `len()` function to obtain
        the count of elements in the linked list.

        Returns:
            int: The number of elements (nodes) in the linked list.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(1)
            >>> ll.add_to_front(2)
            >>> len(ll)
            2
        """
        ...
    
    def __reversed__(self) -> Iterable[NodeType[T]]:
        """
        Iterates over all nodes in the linked list in reverse order.

        This method provides an iterator that yields nodes in the linked list starting
        from the last node and moving towards the head. It is implemented using the
        `reverse` method to reverse the linked list and then iterate over the reversed list.

        Returns:
            Iterable[Node[T]]: An iterator that yields each node in the linked list
                                in reverse order.

        Example:
            >>> ll = LinkedList[int]()
            >>> ll.add_to_front(1)
            >>> ll.add_to_front(2)
            >>> ll.add_to_front(3)
            >>> for node_in_the_list in reversed(ll):
            >>>     print(node_in_the_list.data)
            1
            2
            3
        """
        ...
    
    def __getitem__(self, index: int) -> Optional[NodeType[T]]:
        """
       Retrieves the data of the node at the specified index in the linked list.

       This method allows access to nodes using both positive and negative indices. Positive indices
       start from 0 (head of the list), and negative indices count backward from the end of the list
       (e.g., -1 refers to the last node). It provides an interface similar to list indexing in Python.

       Args:
           index (int): The position of the node to retrieve. Positive indices start from 0 (head
                        of the list), and negative indices count backward from the end of the list.

       Returns:
           T: The data of the node at the specified index.

       Raises:
           IndexError: If the index is out of the valid range of the list (negative or greater than
                       or equal to the size of the list).

       Example:
           >>> ll = LinkedList[int]()
           >>> ll.add_to_front(1)
           >>> ll.add_to_front(2)
           >>> ll[1]
           1
           >>> ll[-1]
           1
       """
        ...
    
    def __setitem__(self, index: int, value: NodeType[T]) -> None:
        ...
    


