"""
This type stub file was generated by pyright.
"""

from typing import Optional

class ResultType[T,E]:
    def __init__(self, value: Optional[T] = ..., error: Optional[E] = ...) -> None:
        ...
    
    def is_ok(self): # -> bool:
        ...
    
    def is_err(self): # -> bool:
        ...
    
    def unwrap(self) -> T:
        ...
    
    def unwrap_err(self) -> E:
        ...
    


