/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun countToBillion(): Int {
    var count = 0
    for (i in 0..1_000_000_000) {
        count += i % 2 // Add some variation to prevent loop optimization, Kotlin is hella smart! 
    }
    return count
}

fun main() {
    println(App().greeting)
}
