import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import { links } from "@/lib/data/navLinks";

// Styles

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Make Predictions",
  description: "Generated by Tomodachi Inc.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black relative`}
        >
          <NavBar links={links} />

          <header className="flex justify-end items-center p-4 gap-4 h-16">
            Header
          </header>
          {children}
        </body>
      </html>
  );
}
